<a href="https://colab.research.google.com/github/niharika-kundur/play_store_app_review_analysis/blob/main/Copy_of_Play_Store_App_Review_Analysis_Capstone_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## <b> The Play Store apps data has enormous potential to drive app-making businesses to success. Actionable insights can be drawn for developers to work on and capture the Android market. </b>

## <b> Each app (row) has values for catergory, rating, size, and more. Another dataset contains customer reviews of the android apps.</b>

## <b> Explore and analyze the data to discover key factors responsible for app engagement and success. </b>

In [ ]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
playstore_data_path='/content/drive/MyDrive/EDA /Copy of Play Store Data.csv'
user_reviews__path='/content/drive/MyDrive/EDA /Copy of User Reviews.csv'
playstore_data_df=pd.read_csv(playstore_data_path)
user_reviews_df=pd.read_csv(user_reviews__path)

In [ ]:
playstore_data_df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [ ]:
user_reviews_df.head()

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462
2,10 Best Foods for You,NaN,NaN,NaN,NaN
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000

In [ ]:
print(playstore_data_df.shape)
print(user_reviews_df.shape)

(10841, 13)
(64295, 5)

## ***.DATA CLEANING***

In [ ]:
# finding missing values in the data
print( ' ' ' missing values are as following' + '\n\n' + ' ' '*'*20)

playstore_data_df.isnull().sum()

  missing values are as following

 * * * * * * * * * * * * * * * * * * * *

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

From the above result , it can be stated that the rating column has highest amount of null values i.e.,1474 ,current version column has 8 null values, Android version column has 3 null values and content rating and type both have 1 null value each .And the rest has no null values.



Data can contain duplicate values,NaN type and wrong datatype so that we need to clean the data

In [ ]:
#checking for duplicate values 
playstore_data_df[playstore_data_df.duplicated(subset=['App'], keep='first' )]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
229,Quick PDF Scanner + OCR FREE,BUSINESS,4.2,80805,Varies with device,"5,000,000+",Free,0,Everyone,Business,"February 26, 2018",Varies with device,4.0.3 and up
236,Box,BUSINESS,4.2,159872,Varies with device,"10,000,000+",Free,0,Everyone,Business,"July 31, 2018",Varies with device,Varies with device
239,Google My Business,BUSINESS,4.4,70991,Varies with device,"5,000,000+",Free,0,Everyone,Business,"July 24, 2018",2.19.0.204537701,4.4 and up
256,ZOOM Cloud Meetings,BUSINESS,4.4,31614,37M,"10,000,000+",Free,0,Everyone,Business,"July 20, 2018",4.1.28165.0716,4.0 and up
261,join.me - Simple Meetings,BUSINESS,4.0,6989,Varies with device,"1,000,000+",Free,0,Everyone,Business,"July 16, 2018",4.3.0.508,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10715,FarmersOnly Dating,DATING,3.0,1145,1.4M,"100,000+",Free,0,Mature 17+,Dating,"February 25, 2016",2.2,4.0 and up
10720,Firefox Focus: The privacy browser,COMMUNICATION,4.4,36981,4.0M,"1,000,000+",Free,0,Everyone,Communication,"July 6, 2018",5.2,5.0 and up
10730,FP Notebook,MEDICAL,4.5,410,60M,"50,000+",Free,0,Everyone,Medical,"March 24, 2018",2.1.0.372,4.4 and up
10753,Slickdeals: Coupons & Shopping,SHOPPING,4.5,33599,12M,"1,000,000+",Free,0,Everyone,Shopping,"July 30, 2018",3.9,4.4 and up
10768,AAFP,MEDICAL,3.8,63,24M,"10,000+",Free,0,Everyone,Medical,"June 22, 2018",2.3.1,5.0 and up

The above output retrieved 1181 rows of duplicate data. So we need to drop this duplicate data

In [ ]:
#droping the  duplicates from App column.
playstore_data_df.drop_duplicates(subset=['App'],keep='first', inplace=True, ignore_index=True)

Checking if the duplicate data is removed or not.

In [ ]:
playstore_data_df[playstore_data_df.duplicated(subset=['App'], keep='first' )]

Empty DataFrame
Columns: [App, Category, Rating, Reviews, Size, Installs, Type, Price, Content Rating, Genres, Last Updated, Current Ver, Android Ver]
Index: []

All the duplicate columns are successfully dropped.

In [ ]:
playstore_data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9660 entries, 0 to 9659
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             9660 non-null   object
 1   Category        9660 non-null   object
 2   Rating          8197 non-null   float64
 3   Reviews         9660 non-null   object
 4   Size            9660 non-null   object
 5   Installs        9660 non-null   object
 6   Type            9659 non-null   object
 7   Price           9660 non-null   object
 8   Content Rating  9659 non-null   object
 9   Genres          9660 non-null   object
 10  Last Updated    9660 non-null   object
 11  Current Ver     9652 non-null   object
 12  Android Ver     9657 non-null   object
dtypes: float64(1), object(12)
memory usage: 981.2+ KB

In [ ]:
playstore_data_df.isnull().sum()

App                  0
Category             0
Rating            1463
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

 Here The Rating seem to have a very high number of missing observations.The current ver, Android ver, Type and content rating also have missing values, but they’re pretty negligible compared to Rating.

Replacing all null values with their appropriate values using **aggregate** **functions** such as **mean**,**median**,**mode**